version: "3.1"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
  spring-mongodb:
    image: spring-mongodb:1.0
    container_name: spring-mongodb
    ports:
      - "8080:8080"

    depends_on:
      - mongodb

    links:
      - mongodb






